
trigger:
  branches:
    include:
      - main
      - feature/*


pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest


variables:
  - group: auth-variables

stages:

- stage: Push_with_Feature_Branch
  displayName: 'Push with Feature Branch'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
  jobs:
    - job: Test_Branch
      displayName: 'Branch Job / Build and Test '
      steps: 
        - task: UseNode@1
          inputs:
            version: '22.x'

        - script: npm ci      
          displayName: 'Install Dependencies (including dev)'

        - task: WhiteSource@21
          inputs:
            cwd: '$(System.DefaultWorkingDirectory)'

        - script: | 
            npm test:unit
          displayName: 'Branch / Run Tests with Coverage'
