
trigger:
  branches:
    include:
      - main
      - feature/*


pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest


variables:
  - group: auth-variables

stages:
- stage: Install_Node_JS
  displayName: 'Install Node Js and dependencies'
  jobs:
    - job:  Install_Node_JS
      displayName: 'Install Node Js and dependencies'
      steps:
        - task: UseNode@1
          inputs:
            version: '22.x'
          displayName: 'Install Node.js'

        - script: npm ci
          displayName: 'Install Dependencies'

        # - task: WhiteSource@21
        #   inputs:
        #     cwd: '$(System.DefaultWorkingDirectory)'

- stage: Push_with_Feature_Branch
  displayName: 'Push with Feature Branch'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
  jobs:
    - job: Test_Branch
      displayName: 'Branch Job / Build and Test '
      steps: 
        - task: UseNode@1
          inputs:
            version: '22.x'

        - script: npm ci      
          displayName: 'Install Dependencies (including dev)'

        - script: | 
            npm test
          displayName: 'Branch / Run Tests with Coverage'
