sonar.projectKey=NovaShop-Project
sonar.projectName=Auth Service
sonar.projectVersion=1.0

# حدد مجلدات الكود
sonar.sources=.

# استبعد الملفات والمجلدات اللي مالهاش لازمة
sonar.exclusions=node_modules/**,coverage/**,test/**

# لو عندك اختبارات تغطية (coverage)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# اللغة الافتراضية
sonar.language=js
